### ISSUE TITLE
Set default repr=False in @attr.s(), but have individual attrs overwrite

### ISSUE THREAD

**Issue by econchick** [hynek/attrs#7]
Current behavior:

```
In [8]: @attr.s(repr=False)
   ...: class Foo(object):
   ...:     x = attr.ib()
   ...:     y = attr.ib(repr=True)
   ...:

In [9]: f = Foo(x="foo", y="bar")

In [10]: f
Out[10]: <__main__.Foo at 0x10a139c50>
```

Desired behavior:

```
In [8]: @attr.s(repr=False)
   ...: class Foo(object):
   ...:     x = attr.ib()
   ...:     y = attr.ib(repr=True)
   ...:

In [9]: f = Foo(x="foo", y="bar")

In [10]: f
Out[10]: Foo(y="bar")
````

Especially useful when you have many attr.ibs but only want one in to actually be in the repr.

**Comment by hynek** [comment]
I’m not sure how I feel about this; in any case the `@attr.s(repr=False)` would have to be renamed to `@attr.s(repr_default=False`) and the logic changed such that it is detected whether a repr (et al) should be created by looking at all attributes instead of at the setting.

Gotta sleep over that. :)

**Comment by hynek** [comment]
So I’m not doing this for now because while it saves some typing, it feels like it adds cognitive complexity that makes it harder to understand and adds code complexity that doesn’t seem worth it…sorry.
